{{- if .Values.serviceAccount.create }}
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "mimir-provisioning.fullname" . }}
roleRef:
  kind: Role
  name: {{ include "mimir-provisioning.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: {{ include "mimir-provisioning.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
